salesforce-spacetraders/force-app/main/default/objects/User/fields/spaceTraderId__c.field-meta.xml
<CustomField>
    <fullName>spaceTraderId__c</fullName>
    <description>Id field for the username returned from the spacetraders API</description>
    <externalId>true</externalId>
    <label>spaceTrader Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-spacetraders/force-app/main/default/objects/User/fields/spaceTraderToken__c.field-meta.xml
<CustomField>
    <fullName>spaceTraderToken__c</fullName>
    <description>Store the user token for spacetraders api</description>
    <label>spacetradersToken</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-spacetraders/force-app/main/default/objects/User/fields/spaceTraderUsername__c.field-meta.xml
<CustomField>
    <fullName>spaceTraderUsername__c</fullName>
    <description>Username field for the username returned from the spacetraders API</description>
    <externalId>true</externalId>
    <label>spacetradersUsername</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-spacetraders/force-app/main/default/classes/generateUserAndToken.cls
public class generateUserAndToken {
    public static void generate(String userName) {
        User sf_user = getCurrentUser();

        HttpResponse res = doCallout(userName);

        //create http request
        spaceTrader st_user = parseResponse(res);

        System.debug('DEBUG st_user.token: ' + st_user.token);

        sf_user = mapResponseToBody(st_user, sf_user);

        System.debug('DEBUG sf_user.token: ' + st_user.token);
        try {
            update sf_user;
        } catch (Exception ex)
        {
            System.debug('ERROR in updating user: ' + ex);
        }
    }

    public static HttpResponse doCallout(String userName)
    {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://api.spacetraders.io/users/' + userName + '/token');
        req.setMethod('POST');
        HttpResponse res = h.send(req);

        return res;
    }

    public static User getCurrentUser()
    {
        User currentUser = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
        return currentUser;
    }

    @testVisible
    private static spaceTrader parseResponse(HttpResponse res)
    {
        System.debug(res.getBody());
        spaceTrader spacetraderUser = (spaceTrader)JSON.deserialize(res.getBody(), spaceTrader.class);

        spaceTrader.parse(res.getBody());

        //System.debug(spacetraderUser);
        return spacetraderUser;
    }

    private static User mapResponseToBody(spaceTrader st_user, User sf_user)
    {
        sf_user.spaceTraderToken__c = st_user.token;
        System.debug('DEBUG sf_user.spaceTraderToken__c: ' + sf_user.spaceTraderToken__c);
        sf_user.spaceTraderUsername__c = st_user.user.username;
        sf_user.spaceTraderId__c = st_user.user.id;
        return sf_user;
    }

    // {
    //     "token": "215bb7e6-4a69-47d7-a158-e71e2578dccb",
    //     "user": {
    //         "id": "ckmqdaxw046048615s6oabhoc7v",
    //         "username": "test3",
    //         "picture": null,
    //         "email": null,
    //         "credits": 0,
    //         "createdAt": "2021-03-26T13:55:59.376Z",
    //         "updatedAt": "2021-03-26T13:55:59.376Z"
    //     }
    // }
}